import XCTest
@testable import OpenMeteoSwift

final class OpenMeteoSwiftTests: XCTestCase {
    let geocodeData2 = """
    {
        "results": [
            {
                "id": 2988507,
                "name": "Paris",
                "latitude": 48.85341,
                "longitude": 2.3488,
                "elevation": 42.0,
                "feature_code": "PPLC",
                "country_code": "FR",
                "admin1_id": 3012874,
                "admin2_id": 2968815,
                "timezone": "Europe/Paris",
                "population": 2138551,
                "postcodes": [
                    "75001",
                    "75020",
                    "75002",
                    "75003",
                    "75004",
                    "75005",
                    "75006",
                    "75007",
                    "75008",
                    "75009",
                    "75010",
                    "75011",
                    "75012",
                    "75013",
                    "75014",
                    "75015",
                    "75016",
                    "75017",
                    "75018",
                    "75019"
                ],
                "country_id": 3017382,
                "country": "France",
                "admin1": "Île-de-France",
                "admin2": "Paris"
            },
            {
                "id": 3044171,
                "name": "Tamási",
                "latitude": 46.63333,
                "longitude": 18.28333,
                "elevation": 126.0,
                "feature_code": "PPLA2",
                "country_code": "HU",
                "admin1_id": 3043845,
                "timezone": "Europe/Budapest",
                "population": 9682,
                "country_id": 719819,
                "country": "Hungary",
                "admin1": "Tolna megye"
            },
            {
                "id": 589604,
                "name": "Päri",
                "latitude": 58.34528,
                "longitude": 25.50333,
                "elevation": 84.0,
                "feature_code": "PPL",
                "country_code": "EE",
                "admin1_id": 587590,
                "admin2_id": 11054708,
                "admin3_id": 11050931,
                "timezone": "Europe/Tallinn",
                "population": 475,
                "country_id": 453733,
                "country": "Estonia",
                "admin1": "Viljandimaa",
                "admin2": "Viljandi vald",
                "admin3": "Päri küla"
            },
            {
                "id": 9035629,
                "name": "Pari",
                "latitude": 43.06334,
                "longitude": 11.31974,
                "elevation": 353.0,
                "feature_code": "PPL",
                "country_code": "IT",
                "admin1_id": 3165361,
                "admin3_id": 3178567,
                "timezone": "Europe/Rome",
                "population": 204,
                "country_id": 3175395,
                "country": "Italy",
                "admin1": "Tuscany",
                "admin3": "Civitella Paganico"
            },
            {
                "id": 121428,
                "name": "Parī",
                "latitude": 36.87771,
                "longitude": 47.4186,
                "elevation": 1708.0,
                "feature_code": "PPL",
                "country_code": "IR",
                "admin1_id": 111452,
                "timezone": "Asia/Tehran",
                "country_id": 130758,
                "country": "Iran",
                "admin1": "Zanjan"
            },
            {
                "id": 589603,
                "name": "Päri",
                "latitude": 58.98333,
                "longitude": 25.23333,
                "elevation": 81.0,
                "feature_code": "PPL",
                "country_code": "EE",
                "admin1_id": 589115,
                "admin2_id": 7522401,
                "admin3_id": 11052732,
                "timezone": "Europe/Tallinn",
                "country_id": 453733,
                "country": "Estonia",
                "admin1": "Raplamaa",
                "admin2": "Rapla vald",
                "admin3": "Suurekivi küla"
            },
            {
                "id": 612508,
                "name": "Pari",
                "latitude": 43.05234,
                "longitude": 42.49307,
                "elevation": 1393.0,
                "feature_code": "PPL",
                "country_code": "GE",
                "admin1_id": 865543,
                "timezone": "Asia/Tbilisi",
                "country_id": 614540,
                "country": "Georgia",
                "admin1": "Samegrelo and Zemo Svaneti"
            },
            {
                "id": 642670,
                "name": "Päri",
                "latitude": 62.36667,
                "longitude": 23.0,
                "elevation": 133.0,
                "feature_code": "PPL",
                "country_code": "FI",
                "admin1_id": 830682,
                "admin2_id": 9610663,
                "admin3_id": 650098,
                "timezone": "Europe/Helsinki",
                "country_id": 660013,
                "country": "Finland",
                "admin1": "South Ostrobothnia",
                "admin2": "Seinäjoki",
                "admin3": "Kurikka"
            },
            {
                "id": 794770,
                "name": "Pari",
                "latitude": 57.67139,
                "longitude": 27.15278,
                "elevation": 212.0,
                "feature_code": "PPL",
                "country_code": "EE",
                "admin1_id": 587448,
                "admin2_id": 7522483,
                "admin3_id": 11053870,
                "timezone": "Europe/Tallinn",
                "country_id": 453733,
                "country": "Estonia",
                "admin1": "Võrumaa",
                "admin2": "Võru Parish",
                "admin3": "Pari küla"
            },
            {
                "id": 801690,
                "name": "Pari",
                "latitude": 42.81639,
                "longitude": 45.64667,
                "elevation": 948.0,
                "feature_code": "PPL",
                "country_code": "RU",
                "admin1_id": 569665,
                "timezone": "Europe/Moscow",
                "country_id": 2017370,
                "country": "Russia",
                "admin1": "Chechnya Republic"
            }
        ],
        "generationtime_ms": 2.2610426
    }
    """.data(using: .utf8)!
    let geocodeData1 = """
{
"results": [
    {
        "id": 6252001,
        "name": "United States",
        "latitude": 39.76,
        "longitude": -98.5,
        "elevation": 543.0,
        "feature_code": "PCLI",
        "country_code": "US",
        "population": 327167434,
        "country_id": 6252001,
        "country": "United States"
    },
    {
        "id": 4078348,
        "name": "Mount Vernon",
        "latitude": 31.08518,
        "longitude": -88.01333,
        "elevation": 11.0,
        "feature_code": "PPL",
        "country_code": "US",
        "admin1_id": 4829764,
        "admin2_id": 4076607,
        "timezone": "America/Chicago",
        "population": 1518,
        "postcodes": [
            "36560"
        ],
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Alabama",
        "admin2": "Mobile"
    },
    {
        "id": 4796775,
        "name": "U.S. Virgin Islands",
        "latitude": 18.34829,
        "longitude": -64.98348,
        "elevation": 82.0,
        "feature_code": "PCLD",
        "country_code": "VI",
        "timezone": "America/St_Thomas",
        "population": 106977
    },
    {
        "id": 5051056,
        "name": "United States Point",
        "latitude": 48.10212,
        "longitude": -91.57179,
        "elevation": 416.0,
        "feature_code": "CAPE",
        "country_code": "US",
        "admin1_id": 5037779,
        "admin2_id": 5033738,
        "timezone": "America/Atikokan",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Minnesota",
        "admin2": "Lake"
    },
    {
        "id": 6172004,
        "name": "United States Range",
        "latitude": 82.41879,
        "longitude": -67.99236,
        "elevation": 1860.0,
        "feature_code": "MT",
        "country_code": "CA",
        "admin1_id": 6091732,
        "timezone": "America/Pangnirtung",
        "country_id": 6251999,
        "country": "Canada",
        "admin1": "Nunavut"
    },
    {
        "id": 5442479,
        "name": "United States Mountain",
        "latitude": 37.95666,
        "longitude": -107.73923,
        "elevation": 3967.0,
        "feature_code": "MT",
        "country_code": "US",
        "admin1_id": 5417618,
        "admin2_id": 5433677,
        "timezone": "America/Denver",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Colorado",
        "admin2": "Ouray"
    },
    {
        "id": 5683903,
        "name": "United States Number 2 Dam",
        "latitude": 45.16332,
        "longitude": -105.66222,
        "elevation": 1078.0,
        "feature_code": "DAM",
        "country_code": "US",
        "admin1_id": 5667009,
        "admin2_id": 5672326,
        "timezone": "America/Denver",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Montana",
        "admin2": "Powder River"
    },
    {
        "id": 4140844,
        "name": "United States Navy Memorial",
        "latitude": 38.89928,
        "longitude": -77.02192,
        "elevation": 14.0,
        "feature_code": "PRK",
        "country_code": "US",
        "admin1_id": 4138106,
        "admin2_id": 4140987,
        "timezone": "America/New_York",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Washington, D.C.",
        "admin2": "Washington"
    },
    {
        "id": 4134490,
        "name": "United States Mag Corp Lake Dam",
        "latitude": 35.90341,
        "longitude": -91.67347,
        "elevation": 119.0,
        "feature_code": "DAM",
        "country_code": "US",
        "admin1_id": 4099753,
        "admin2_id": 4115832,
        "admin3_id": 4116453,
        "timezone": "America/Chicago",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Arkansas",
        "admin2": "Independence",
        "admin3": "Jefferson Township"
    },
    {
        "id": 7251415,
        "name": "United States Lock Number Eight",
        "latitude": 37.74562,
        "longitude": -84.58707,
        "elevation": 160.0,
        "feature_code": "DAM",
        "country_code": "US",
        "admin1_id": 6254925,
        "admin2_id": 4292570,
        "timezone": "America/New_York",
        "country_id": 6252001,
        "country": "United States",
        "admin1": "Kentucky",
        "admin2": "Garrard"
    }
],
"generationtime_ms": 0.9429455
}
""".data(using: .utf8)!
}

struct OpenMeteoTestError: LocalizedError {
    var message: String
}
